# Generated by Django 2.2.6 on 2019-10-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='person',
            field=models.PositiveIntegerField(),
        ),
    ]
