# Generated by Django 2.2.6 on 2019-10-08 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.BooleanField(default=False)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=160)),
                ('prenom', models.CharField(max_length=160)),
                ('photo', models.ImageField(upload_to='photo_presonnel')),
            ],
            options={
                'verbose_name': 'Cuisinier',
                'verbose_name_plural': 'Cuisiniers',
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.BooleanField(default=False)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=160)),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.BooleanField(default=False)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('lien', models.URLField()),
                ('icon', models.ManyToManyField(related_name='social_icon', to='entreprise.Social')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presonnel_social', to='entreprise.Personnel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.BooleanField(default=False)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='logo')),
                ('license_site', models.CharField(max_length=255)),
                ('working_hour', models.ManyToManyField(related_name='working_config', to='configuration.WorkingHour')),
            ],
            options={
                'verbose_name': 'Presentation',
                'verbose_name_plural': 'Presentations',
            },
        ),
        migrations.AddField(
            model_name='personnel',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poste_presonnel', to='entreprise.Poste'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='social',
            field=models.ManyToManyField(related_name='social_chef', to='entreprise.Social'),
        ),
    ]
