# Generated by Django 2.2.5 on 2019-10-09 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_ent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.BooleanField(default=False)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('lien', models.URLField()),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_icon', to='configuration.Social')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='social',
        ),
        migrations.DeleteModel(
            name='Social',
        ),
        migrations.AddField(
            model_name='social_ent',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_social', to='entreprise.Personnel'),
        ),
    ]
